php:
  build: .
  ports:
    - 80:80
    - 443:443
  volumes:
    - .:/var/www/html
  links:
  - db

db:
  image: mysql:5.7
  ports:
  - 3306:3306
  volumes:
  - /var/lib/mysql
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=vendas

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
    - db
  ports:
    - 8080:80
  environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306